#!/bin/bash

docker build -t grpc-ros-test .

docker run -it \
    --network="host" \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    -p 50051 \
    grpc-ros-test
#     --env="ROS_IP=$ROS_IP" \
    # --env="ROS_MASTER_URI=$ROS_MASTER_URI" \